name: github pages

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup swarm
        run: |
          printf ${{ secrets.KEY_PASS }} > password
          mkdir -p ${HOME}/.ethereum/keystore
          printf ${{ secrets.KEY_FILE }} > ${HOME}/.ethereum/keystore/UTC--2021-01-08T12-53-49.262522636Z--780872df1a06a602db22ce66a0ff5a19ac4715da
          wget https://ethswarm.blob.core.windows.net/builds/swarm-linux-amd64-0.5.7-5ccfd995.tar.gz -O swarm.tar.gz
          tar --strip-components 1 -xzf swarm.tar.gz
      - name: Swarm upload
        run: |
          FEED=$(./swarm --bzzapi https://swarm-public-0-swarm.prod.swarm-gateways.net --verbosity 6 --recursive --defaultpath ./publish/index.html up ./publish)
          ./swarm --bzzapi https://swarm-gateways.net/ --verbosity 6 --password password feed update 0x"${FEED}"
